#!/bin/bash
#
# Count all of the lines in the lines database

for shard in /var/index/lines/shard_*.sst; do
    ./bin/inspect_shard $shard;
done | awk ' /max_value/ { if ($3 > m) { m = $3 } } END { print m }
