#!/usr/bin/env python

import optparse
import sys

from pygments import formatters
from pygments import styles

if __name__ == '__main__':
    parser = optparse.OptionParser()
    parser.add_option('-l', '--list', action='store_true', help='list colors')
    opts, args = parser.parse_args()
    if opts.list:
        for style in sorted(styles.get_all_styles()):
            print style
    else:
        print formatters.HtmlFormatter(
            style=sys.argv[1]).get_style_defs('.highlight')
